## **INSURANCE FRAUD**

**IMPORTING NECESSARY LIBRARIES**

In [ ]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

import warnings
warnings.filterwarnings("ignore")
#Please ignore the warnings with version change

from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive



Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


**IMPORTING THE DATA FILES AND ASSIGNING TRAINING AND TEST DATA**

In [ ]:
trainfile = r'/gdrive/My Drive/CIS 508/Insurance Fraud - TRAIN-3000.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/CIS 508/Insurance Fraud -TEST-12900.csv'
testData = pd.read_csv(testfile)  #creates a dataframe

# Print the Training and Testing Data Shape
print(trainData.shape)
print(testData.shape)


(2999, 32)
(12918, 32)


**COLUMNS OF THE TRAINING DATA**

In [ ]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 2999 non-null   object
 1   WEEKOFMONTH           2999 non-null   int64 
 2   DAYOFWEEK             2999 non-null   object
 3   MAKE                  2999 non-null   object
 4   ACCIDENTAREA          2999 non-null   object
 5   DAYOFWEEKCLAIMED      2999 non-null   object
 6   MONTHCLAIMED          2999 non-null   object
 7   WEEKOFMONTHCLAIMED    2999 non-null   int64 
 8   SEX                   2999 non-null   object
 9   MARITALSTATUS         2999 non-null   object
 10  AGE                   2999 non-null   int64 
 11  FAULT                 2999 non-null   object
 12  POLICYTYPE            2999 non-null   object
 13  VEHICLECATEGORY       2999 non-null   object
 14  VEHICLEPRICE          2999 non-null   object
 15  REPNUMBER             2999 non-null   

**COLUMNS OF THE TEST DATA**

In [ ]:
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12918 entries, 0 to 12917
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 12918 non-null  object
 1   WEEKOFMONTH           12918 non-null  int64 
 2   DAYOFWEEK             12918 non-null  object
 3   MAKE                  12918 non-null  object
 4   ACCIDENTAREA          12918 non-null  object
 5   DAYOFWEEKCLAIMED      12918 non-null  object
 6   MONTHCLAIMED          12918 non-null  object
 7   WEEKOFMONTHCLAIMED    12918 non-null  int64 
 8   SEX                   12918 non-null  object
 9   MARITALSTATUS         12918 non-null  object
 10  AGE                   12918 non-null  int64 
 11  FAULT                 12918 non-null  object
 12  POLICYTYPE            12918 non-null  object
 13  VEHICLECATEGORY       12918 non-null  object
 14  VEHICLEPRICE          12918 non-null  object
 15  REPNUMBER             12918 non-null

**RETREIVING ALL THE COLUMN NAMES FROM THE TRAINING AND TESTING DATA**

In [ ]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'FRAUDFOUND']
['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'F

**SEPARATE THE FRAUD FOUND I.E., TARGET COLUMN FROM TRAINING DATA**

In [ ]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['FRAUDFOUND']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['FRAUDFOUND']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(2999, 31)
(2999, 1)
Test Set shape:
(12918, 31)
(12918, 1)


**LIST THE CATEGORICAL FEATURES OF THE DATA SET**

In [ ]:
#List of Categorical Features
categoricalFeatures = ['MONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'BASEPOLICY']

**IMPLEMENTING ONE-HOT ENCODING ON THE TRAINING DATA**

In [ ]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
1740            2                   2   62         15         400   
1841            2                   2   28          3         400   
578             4                   1   33         14         400   
2098            4                   3   29          4         400   
1861            1                   2   52          4         700   

      DRIVERRATING  YEAR  x0_Apr  x0_Aug  x0_Dec  ...  x21_4_to_8_years  \
1740             3  1995     0.0     0.0     0.0  ...               0.0   
1841             2  1996     1.0     0.0     0.0  ...               0.0   
578              1  1995     0.0     0.0     0.0  ...               0.0   
2098             1  1996     0.0     0.0     0.0  ...               0.0   
1861             3  1995     0.0     0.0     0.0  ...               0.0   

      x21_no_change  x21_under_6_months  x22_1-vehicle  x22_2-vehicles  \
1740            1.0                 0.0            1.0             0.0   
1841            1.0                 0.0            1.0             0.0   
578             1.0                 0.0            1.0             0.0   
2098            1.0                 0.0            1.0             0.0   
1861            1.0                 0.0            1.0             0.0   

      x22_3_to_4  x22_5_to_8  x23_All_Perils  x23_Collision  x23_Liability  
1740         0.0         0.0             1.0            0.0            0.0  
1841         0.0         0.0             0.0            1.0            0.0  
578          0.0         0.0             0.0            1.0            0.0  
2098         0.0         0.0             1.0            0.0            0.0  
1861         0.0         0.0             0.0            1.0            0.0  

[5 rows x 139 columns]

**IMPLEMENTING ONE-HOT ENCODING ON THE TEST DATA**

In [ ]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
7388            4                   5   58          8         400   
3554            4                   5   35         14         400   
538             1                   1   65          1         400   
5043            1                   2   28         16         400   
3861            1                   2   40          5         400   

      DRIVERRATING  YEAR  x0_Apr  x0_Aug  x0_Dec  ...  x21_4_to_8_years  \
7388             4  1996     0.0     0.0     0.0  ...               0.0   
3554             4  1996     0.0     0.0     0.0  ...               0.0   
538              1  1994     0.0     0.0     0.0  ...               0.0   
5043             4  1994     0.0     0.0     0.0  ...               0.0   
3861             2  1995     0.0     0.0     0.0  ...               0.0   

      x21_no_change  x21_under_6_months  x22_1-vehicle  x22_2-vehicles  \
7388            1.0                 0.0            1.0             0.0   
3554            1.0                 0.0            1.0             0.0   
538             1.0                 0.0            1.0             0.0   
5043            1.0                 0.0            1.0             0.0   
3861            1.0                 0.0            1.0             0.0   

      x22_3_to_4  x22_5_to_8  x23_All_Perils  x23_Collision  x23_Liability  
7388         0.0         0.0             0.0            0.0            1.0  
3554         0.0         0.0             0.0            1.0            0.0  
538          0.0         0.0             0.0            0.0            1.0  
5043         0.0         0.0             0.0            1.0            0.0  
3861         0.0         0.0             0.0            0.0            1.0  

[5 rows x 139 columns]

**IMPLEMENT DECISION TREE CLASSIFIER ON TRAINING DATA**

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

**HYPERPARAMETER TUNING FOR THE DECISION TREE CLASSIFIER**

In [ ]:
#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth': 
            range(5,30,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=5)
dt_random.fit(Xtrain, Ytrain)
# dtr = pd.Dataframe(dt_random.cv_results_)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 40, 'max_depth': 17, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.907493
--- 2.9106905460357666 seconds ---


In [ ]:
# dtr.loc[dtr['rank_test_score']==1]

**GRID SEARCH**

In [ ]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
dtr = pd.DataFrame(dt_random.cv_results_)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree
{'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.896220
--- 96.07961320877075 seconds ---


In [ ]:
dtr.loc[dtr['rank_test_score']==1]

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
16       0.018875      0.000369         0.003783        0.000107   

   param_min_samples_leaf param_max_depth param_criterion  \
16                     40               5         entropy   

                                               params  split0_test_score  \
16  {'min_samples_leaf': 40, 'max_depth': 5, 'crit...           0.897238   

    split1_test_score  split2_test_score  split3_test_score  \
16           0.891593           0.893805           0.894912   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
16           0.900442         0.895598        0.003029                1

In [ ]:
dtr[['param_min_samples_leaf', 'param_max_depth', 'param_criterion', 'rank_test_score']].sort_values('rank_test_score').head()

param_min_samples_leaf param_max_depth param_criterion  rank_test_score
16                     40               5         entropy                1
17                     20              29            gini                2
21                     70              23            gini                3
22                     90              11            gini                4
20                     90              25         entropy                5

**Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier**

In [ ]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

**OBTAINING MODEL ACCURACY FOR DECISION TREE USING RANDOM SEARCH**

In [ ]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.907493420034061
Confusion Matrix for Decision Tree:
[[11578   842]
 [  353   145]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.93      0.95     12420
         Yes       0.15      0.29      0.20       498

    accuracy                           0.91     12918
   macro avg       0.56      0.61      0.57     12918
weighted avg       0.94      0.91      0.92     12918

[0.74615385 0.73990385 0.54375    0.5        0.55696203]


**OBTAINING ACCURACY FOR DECISION TREE USING GRID SEARCH**

In [ ]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtGrid_predict))

Test Accuracy: 0.8974299427155906
Confusion Matrix for Decision Tree:
[[11427   993]
 [  332   166]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.92      0.95     12420
         Yes       0.14      0.33      0.20       498

    accuracy                           0.90     12918
   macro avg       0.56      0.63      0.57     12918
weighted avg       0.94      0.90      0.92     12918



**IMPLEMENT RANDOM FOREST CLASSIFIER ON TESTING DATA**

In [ ]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier()

**Hyperparameter tuning done for random forest classifier- Random Search**

In [ ]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth': 
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 20, 'min_samples_leaf': 30, 'max_features': 30, 'max_depth': 9}
accuracy Score for Decision Tree:0.929943
--- 10.849988222122192 seconds ---


**Hyperparameter tuning done for random forest classifier- Grid Search**

In [ ]:
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(Xtrain, Ytrain)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Random Forest
{'max_depth': 7, 'max_features': 30, 'min_samples_leaf': 10, 'n_estimators': 30}
accuracy Score for Decision Tree:0.929246
--- 171.80839276313782 seconds ---


**USING THE PARAMETERS OBTAINED FROM HYPER PARAMETER TUNING IN RANDOM FOREST CLASSIFIER**

In [ ]:
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

**Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning**

In [ ]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
clf_cv_score = cross_val_score(rfRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.926072147391237
Confusion Matrix for Decision Tree:
[[11843   577]
 [  378   120]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.95      0.96     12420
         Yes       0.17      0.24      0.20       498

    accuracy                           0.93     12918
   macro avg       0.57      0.60      0.58     12918
weighted avg       0.94      0.93      0.93     12918

[0.75240385 0.56778846 0.53125    0.5        0.55063291]


**Accuracy for Random Forest using Grid Search for Hyperparameter Tuning**

In [ ]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))

Test Accuracy: 0.9614491407338597
Confusion Matrix for Decision Tree:
[[12420     0]
 [  498     0]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.96      1.00      0.98     12420
         Yes       0.00      0.00      0.00       498

    accuracy                           0.96     12918
   macro avg       0.48      0.50      0.49     12918
weighted avg       0.92      0.96      0.94     12918



## **TARGET MARKETING**

**READ PORTUGUESE BANK DATA FILE**

In [ ]:
trainfile = r'/gdrive/My Drive/CIS 508/Portugese Bank Data - TRAIN.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/CIS 508/Portugese Bank Data - TEST.csv'
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)

(4521, 17)
(45211, 17)


**OBTAIN THE TRAINING DATA INFORMATION**



In [ ]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


**OBTAIN THE TESTING DATA INFORMATION**


In [ ]:
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


**LIST THE COLUMNS IN THE DATA**

In [ ]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']


**SEPARATE TARGET COLUMN FROM TRAINING AND TESTING DATA**

In [ ]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['y']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['y']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(4521, 16)
(4521, 1)
Test Set shape:
(45211, 16)
(45211, 1)


**LIST THE CATEGORICAL DATA**

In [ ]:
#List of Categorical Features
categoricalFeatures = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

**ONE HOT ENCODING OF TRAINING DATA**

In [ ]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

age  balance  day  duration  campaign  pdays  previous  x0_admin.  \
1073   30      726   16        39         1    342         3        0.0   
882    50       94   22       184         4     -1         0        0.0   
2413   36      257   12        86         2     -1         0        0.0   
4170   50       36   13       104        10     -1         0        0.0   
2326   32       55   15       546         9     -1         0        0.0   

      x0_blue-collar  x0_entrepreneur  ...  x7_jun  x7_mar  x7_may  x7_nov  \
1073             0.0              0.0  ...     0.0     0.0     0.0     0.0   
882              0.0              0.0  ...     0.0     0.0     0.0     0.0   
2413             0.0              0.0  ...     0.0     0.0     1.0     0.0   
4170             0.0              0.0  ...     0.0     0.0     0.0     0.0   
2326             0.0              0.0  ...     0.0     0.0     1.0     0.0   

      x7_oct  x7_sep  x8_failure  x8_other  x8_success  x8_unknown  
1073     0.0     0.0         1.0       0.0         0.0         0.0  
882      0.0     0.0         0.0       0.0         0.0         1.0  
2413     0.0     0.0         0.0       0.0         0.0         1.0  
4170     0.0     0.0         0.0       0.0         0.0         1.0  
2326     0.0     0.0         0.0       0.0         0.0         1.0  

[5 rows x 51 columns]

**ONE HOT ENCODING OF TEST DATA**

In [ ]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

age  balance  day  duration  campaign  pdays  previous  x0_admin.  \
33405   31      648   20       153         1    347         1        0.0   
20786   51       52   13       114         2     -1         0        0.0   
17901   40     1073   30        42         2     -1         0        0.0   
45106   32      660   25       226         2    490         1        0.0   
29669   40      -78    3      2053         4     -1         0        0.0   

       x0_blue-collar  x0_entrepreneur  ...  x7_jun  x7_mar  x7_may  x7_nov  \
33405             1.0              0.0  ...     0.0     0.0     0.0     0.0   
20786             0.0              0.0  ...     0.0     0.0     0.0     0.0   
17901             1.0              0.0  ...     0.0     0.0     0.0     0.0   
45106             0.0              0.0  ...     0.0     0.0     0.0     0.0   
29669             0.0              0.0  ...     0.0     0.0     0.0     0.0   

       x7_oct  x7_sep  x8_failure  x8_other  x8_success  x8_unknown  
33405     0.0     0.0         1.0       0.0         0.0         0.0  
20786     0.0     0.0         0.0       0.0         0.0         1.0  
17901     0.0     0.0         0.0       0.0         0.0         1.0  
45106     1.0     0.0         1.0       0.0         0.0         0.0  
29669     0.0     0.0         0.0       0.0         0.0         1.0  

[5 rows x 51 columns]

**`DECISION TREE CLASSIFIER**

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

In [ ]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth': 
            range(5,30,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=5)
dt_random.fit(Xtrain, Ytrain)
dtr = pd.DataFrame(dt_random.cv_results_)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 50, 'max_depth': 23, 'criterion': 'gini'}
accuracy Score for Decision Tree:0.895026
--- 3.2478930950164795 seconds ---


In [ ]:
dtr.loc[dtr['rank_test_score']== 1]

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
22       0.023522      0.000603         0.003866        0.000098   

   param_min_samples_leaf param_max_depth param_criterion  \
22                     50              23            gini   

                                               params  split0_test_score  \
22  {'min_samples_leaf': 50, 'max_depth': 23, 'cri...           0.897238   

    split1_test_score  split2_test_score  split3_test_score  \
22           0.887168           0.893805           0.896018   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
22           0.899336         0.894713        0.004176                1

In [ ]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
dtr= pd.DataFrame(dt_random.cv_results_)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree
{'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.896220
--- 92.53953433036804 seconds ---


In [ ]:
dtr.loc[dtr['rank_test_score']== 1]

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
22       0.023522      0.000603         0.003866        0.000098   

   param_min_samples_leaf param_max_depth param_criterion  \
22                     50              23            gini   

                                               params  split0_test_score  \
22  {'min_samples_leaf': 50, 'max_depth': 23, 'cri...           0.897238   

    split1_test_score  split2_test_score  split3_test_score  \
22           0.887168           0.893805           0.896018   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
22           0.899336         0.894713        0.004176                1

In [ ]:
dtr[['param_min_samples_leaf', 'param_max_depth', 'param_criterion', 'rank_test_score']].sort_values('rank_test_score').head()

param_min_samples_leaf param_max_depth param_criterion  rank_test_score
22                     50              23            gini                1
19                     40               5            gini                2
10                     20              23         entropy                3
20                     90               9            gini                4
2                      80               9            gini                5

In [ ]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [ ]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest, dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest, dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.895025546880184
Confusion Matrix for Decision Tree:
[[38578  1344]
 [ 3402  1887]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.97      0.94     39922
         yes       0.58      0.36      0.44      5289

    accuracy                           0.90     45211
   macro avg       0.75      0.66      0.69     45211
weighted avg       0.88      0.90      0.88     45211

[0.64401786 0.63509615 0.65139423 0.68192308 0.64197115]


In [ ]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest, dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest, dtGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtGrid_predict))

Test Accuracy: 0.8962199464732035
Confusion Matrix for Decision Tree:
[[38959   963]
 [ 3729  1560]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.91      0.98      0.94     39922
         yes       0.62      0.29      0.40      5289

    accuracy                           0.90     45211
   macro avg       0.77      0.64      0.67     45211
weighted avg       0.88      0.90      0.88     45211



**RANDOM FOREST CLASSIFIER**

In [ ]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier()

In [ ]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth': 
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
rf = pd.DataFrame(rf_random.cv_results_)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 30, 'min_samples_leaf': 20, 'max_features': 30, 'max_depth': 9}
accuracy Score for Decision Tree:0.900998
--- 19.06605553627014 seconds ---


In [ ]:
rf.loc[rf['rank_test_score']==1]

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
18       0.246304      0.004638         0.010489        0.000383   

   param_n_estimators param_min_samples_leaf param_max_features  \
18                 30                     20                 30   

   param_max_depth                                             params  \
18               9  {'n_estimators': 30, 'min_samples_leaf': 20, '...   

    split0_test_score  split1_test_score  split2_test_score  \
18           0.896133           0.901549           0.896018   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
18           0.900442           0.900442         0.898917        0.002355   

    rank_test_score  
18                1

In [ ]:
rf[['param_min_samples_leaf', 'param_max_depth', 'rank_test_score']].sort_values('rank_test_score').head()

param_min_samples_leaf param_max_depth  rank_test_score
18                     20               9                1
9                      30               5                2
17                     20               5                2
19                     50               5                4
13                     30               9                5

In [ ]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier 
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

In [ ]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest, rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest, rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest,rfRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9005109376036805
Confusion Matrix for Decision Tree:
[[38899  1023]
 [ 3475  1814]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.97      0.95     39922
         yes       0.64      0.34      0.45      5289

    accuracy                           0.90     45211
   macro avg       0.78      0.66      0.70     45211
weighted avg       0.89      0.90      0.89     45211

[0.64401786 0.63509615 0.65139423 0.68192308 0.64197115]


In [ ]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))

Test Accuracy: 0.8895843931786512
Confusion Matrix for Decision Tree:
[[39853    69]
 [ 4923   366]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.89      1.00      0.94     39922
         yes       0.84      0.07      0.13      5289

    accuracy                           0.89     45211
   macro avg       0.87      0.53      0.53     45211
weighted avg       0.88      0.89      0.85     45211

